import TransitionEffect from "@/components/TransitionEffect";
import Head from "next/head";
import React from "react";
import Layout from "@/components/Layout";
import Contact from "@/components/Contact";

const Page = () => {
    return (
        <>
            
            <Head>
                <title>Contact Me</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <TransitionEffect />
            <main className="flex w-full flex-col items-center justify-center dark:text-light">
                <Layout className="pt-16">
                    <Contact />
                </Layout>
            </main>
        </>
    );
};

export default Page;
