import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import TransitionEffect from "@/components/TransitionEffect";
import ProfilePic from "../../public/images/profile/developer-pic-2.jpeg";
import Skills from "@/components/Skills";
import About from "@/components/About";
import Experience from "@/components/Experience";
import Education from "@/components/Education";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";
// import Experience from "@/pages/experience";
// import Education from "@/components/Education";

export default function Home() {
    return (
        <>
            <Head>
                <title>Eric Lam</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <TransitionEffect />
            <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
                <Layout className="pt-0 md:pt-16 sm-pt-8">
                    <About />
                    <Experience />
                    <Education  />
                    <Projects />
                    <Contact />
                </Layout>
            </main>
        </>
    );
}
